module.exports = {members: [
["Brent", "aaron.png", "Junior", "https://twitter.com/bbovenzi"],
["Mackenzie", "ashley.png", "Junior", "https://twitter.com/ciaomack"],
["Jeff", "bojia.png", "Junior", "http://jhil.co/"],
["Eric", "dennis.png", "???",""],
["Jackson", "dimeji.png", "Freshman", "https://twitter.com/jaxgeller"],
["Dan", "ed.png", "Junior", "https://github.com/ethernetdan"],
["Tony", "farrukh.png", "Junior", ""],
["Andrew", "gautam.png", "Senior", ""],
["Waj", "jesse.png", "Super Senior", "https://twitter.com/agentwaj"],
["Dan", "jim.png", "Senior", "https://twitter.com/dnosk"],
["Emmanuel", "julian.png", "Senior", "https://twitter.com/emmank2k4"],
["Chike", "logan.png", "Senior", "https://twitter.com/leonchike"],
["Richard", "mack.png", "Senior", ""],
["Jeremy", "michael.png", "Senior", ""],
["Ayana", "nihir.png", "Junior", "http://www.ayanazaire.com/"],
["Chris", "saffana.png", "Sophomore", ""],
["Brett", "suhani.png", "Sophomore", ""],
]
}
